### PR TITLE
svg conversions

### PR DESCRIPTION
**Pull request by ginfuru**
Here are the icons I've converted.

### CODE REVIEW

**Comment by JimiC** [comment]
Many many thanks for your work @ginfuru. I will evaluate them, modify them and submit them on your behalf on their own PR to the `vscode-icons` repo.

**Comment by ginfuru** [comment]
@JimiC No problem! Thanks for accepting the `PR` 👍

**Comment by JimiC** [comment]
@ginfuru I had to reject the following icons:
- editorconfig
- elixir
- phpunit
- plantuml

as they weren't valid svg icons or the icon was crashing `Illustrator`.

The rest will be submitted with a PR as soon as @robertohuertasm has finished with `v5`.

**Comment by ginfuru** [comment]
That's odd - I used Sketch to create the SVGs  - Let me check my settings to make sure I didn't goof on a config.

**Comment by JimiC** [comment]
You can discard `editorconfig`. I asked the devs for an SVG version and they were kind enough to provide one.

**Pull request merged**
